update
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>

diff --git a/.github/workflows/pre-commit.yaml b/.github/workflows/pre-commit.yaml
--- a/.github/workflows/pre-commit.yaml
+++ b/.github/workflows/pre-commit.yaml
@@ -37,14 +37,22 @@ jobs:
         with:
           go-version: ^1.16
 
-      - name: Run pre-commit
-        uses: pre-commit/action@v3.0.0
-        with:
-          extra_args: --all-files --config .pre-commit-config.yaml
-          token: ${{ steps.generate-token.outputs.token }}
+    - name: Install pre-commit
+      run: |
+        python -m pip install pre-commit
+      shell: bash
 
-      - name: Push pre-commit fixes
-        if: always()
-        uses: stefanzweifel/git-auto-commit-action@v4
-        with:
-          commit_message: "ci(pre-commit): autofix"
+    - name: Run pre-commit
+      run: |
+        pre-commit run -a --show-diff-on-failure --color=always --config ${{ inputs.pre-commit-config }}
+      shell: bash
+
+    - name: Push pre-commit fixes
+      if: always() # Push changes even when pre-commit fails
+      run: |
+        if ! git diff --quiet; then
+          git add -u
+          git commit -m "pre-commit fixes"
+          git push
+        fi
+      shell: bash
