update
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>

diff --git a/.github/workflows/pre-commit.yaml b/.github/workflows/pre-commit.yaml
--- a/.github/workflows/pre-commit.yaml
+++ b/.github/workflows/pre-commit.yaml
@@ -37,22 +37,22 @@ jobs:
         with:
           go-version: ^1.16
 
-    - name: Install pre-commit
-      run: |
-        python -m pip install pre-commit
-      shell: bash
+      - name: Install pre-commit
+        run: |
+          python -m pip install pre-commit
+        shell: bash
 
-    - name: Run pre-commit
-      run: |
-        pre-commit run -a --show-diff-on-failure --color=always --config ${{ inputs.pre-commit-config }}
-      shell: bash
+      - name: Run pre-commit
+        run: |
+          pre-commit run -a --show-diff-on-failure --color=always --config ${{ inputs.pre-commit-config }}
+        shell: bash
 
-    - name: Push pre-commit fixes
-      if: always() # Push changes even when pre-commit fails
-      run: |
-        if ! git diff --quiet; then
-          git add -u
-          git commit -m "pre-commit fixes"
-          git push
-        fi
-      shell: bash
+      - name: Push pre-commit fixes
+        if: always() # Push changes even when pre-commit fails
+        run: |
+          if ! git diff --quiet; then
+            git add -u
+            git commit -m "pre-commit fixes"
+            git push
+          fi
+        shell: bash
